version: 2

models:
  - name: int_trips_unioned
    description: "Intermediate model that unions Green and Yellow taxi trip data"
    columns: 
      - name: vendor_id
        description: "The unique identifier for the taxi vendor"
      - name: rate_code_id
        description: "Rate code for the trip"
      - name: pickup_location_id
        description: "TLC Taxi Zone where trip started"
      - name: dropoff_location_id
        description: "TLC Taxi Zone where trip ended"
      - name: pickup_datetime 
        description: "Timestamp when meter was engaged"
      - name: dropoff_datetime
        description: "Timestamp when meter was disengaged"
      - name: store_and_fwd_flag
        description: "Whether the trip record was held in vehicle memory before being sent to the server (Y/N)"
      - name: passenger_count
        description: "Number of passengers in the vehicle"
      - name: trip_distance
        description: "Trip distance in miles"
      - name: trip_type
        description: "Type of taxi service (Green or Yellow)"
      - name: fare_amount
        description: "Time and distance fare"
      - name: extra
        description: "Miscellaneous extras and surcharges"
      - name: mta_tax
        description: "MTA tax"
      - name: tip_amount
        description: "Tip amount (credit card only)"
      - name: tolls_amount
        description: "Total tolls paid"
      - name: ehail_fee
        description: "E-hail service fee (Green taxi only) and cast 0 for Yellow taxi trips"
      - name: improvement_surcharge
        description: "Improvement surcharge"
      - name: total_amount
        description: "Total amount charged"
      - name: service_type
        description: "Type of taxi service (Green or Yellow)"