version: 2

sources:
  - name: nyc_raw_data
    description: "Raw data sources for NYC taxi rides"
    database: de-zoomcamp-project-485521 # GCP Project ID
    schema: datawarehouse_nyc_zoomcamp # dataset name
    tables:
      - name: green_tripdata
        description: Raw green taxi trip records
        columns:
          - name: vendorid
            description: |
              A code indicating the provider associated with the trip record.
                1: 'Creative Mobile Technologies, LLC'
                2: 'VeriFone Inc.'
                4: 'Unknown/Other'
            data_type: integer
            config:
              meta:
                pii: false
                ownership: data_engineering_team
                importance: high
                loaded_at_field: lpep_pickup_datetime
                freshness: null
          - name: lpep_pickup_datetime
            description: Date and time when the meter was engaged
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: ">= '2019-01-01'"
                  config:
                    severity: warn
              - dbt_utils.expression_is_true:
                  expression: "< '2021-01-01'"
                  config:
                    severity: warn
          - name: lpep_dropoff_datetime
            description: Date and time when the meter was disengaged
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: ">= '2019-01-01'"
                  config:
                    severity: warn
              - dbt_utils.expression_is_true:
                  expression: "< '2021-01-01'"
                  config:
                    severity: warn
              - dbt_utils.expression_is_true:
                  expression: ">= lpep_pickup_datetime"
                  config:
                    severity: error
                  name: dropoff_after_pickup
          - name: passenger_count
            description: Number of passengers in the vehicle
          - name: trip_distance
            description: Trip distance in miles
          - name: pulocationid
            description: TLC Taxi Zone where the meter was engaged
          - name: dolocationid
            description: TLC Taxi Zone where the meter was disengaged
          - name: ratecodeid
            description: Rate code (1=Standard, 2=JFK, 3=Newark, 4=Nassau/Westchester, 5=Negotiated, 6=Group)
          - name: store_and_fwd_flag
            description: Trip record held in vehicle memory (Y/N)
          - name: payment_type
            description: Payment method (1=Credit card, 2=Cash, 3=No charge, 4=Dispute, 5=Unknown, 6=Voided)
          - name: fare_amount
            description: Time and distance fare
          - name: extra
            description: Miscellaneous extras and surcharges
          - name: mta_tax
            description: MTA tax
          - name: tip_amount
            description: Tip amount (credit card only)
          - name: tolls_amount
            description: Total tolls paid
          - name: improvement_surcharge
            description: Improvement surcharge
          - name: total_amount
            description: Total amount charged
          - name: trip_type
            description: Trip type (1=Street-hail, 2=Dispatch)
          - name: ehail_fee
            description: E-hail fee

      - name: yellow_tripdata
        description: Raw yellow taxi trip records
        columns:
          - name: vendorid
            description: |
              A code indicating the provider associated with the trip record.
                1: 'Creative Mobile Technologies, LLC'
                2: 'VeriFone Inc.'
                4: 'Unknown/Other'
            data_type: integer
            config:
              meta:
                pii: false
                ownership: data_engineering_team
                importance: high
                loaded_at_field: tpep_pickup_datetime
                freshness: null
          - name: tpep_pickup_datetime
            description: Date and time when the meter was engaged
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: ">= '2019-01-01'"
                  config:
                    severity: warn
              - dbt_utils.expression_is_true:
                  expression: "< '2021-01-01'"
                  config:
                    severity: warn
          - name: tpep_dropoff_datetime
            description: Date and time when the meter was disengaged
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: ">= '2019-01-01'"
                  config:
                    severity: warn
              - dbt_utils.expression_is_true:
                  expression: "< '2021-01-01'"
                  config:
                    severity: warn
              - dbt_utils.expression_is_true:
                  expression: ">= tpep_pickup_datetime"
                  config:
                    severity: error
                  name: dropoff_after_pickup
          - name: passenger_count
            description: Number of passengers in the vehicle
          - name: trip_distance
            description: Trip distance in miles
          - name: pulocationid
            description: TLC Taxi Zone where the meter was engaged
          - name: dolocationid
            description: TLC Taxi Zone where the meter was disengaged
          - name: ratecodeid
            description: Rate code (1=Standard, 2=JFK, 3=Newark, 4=Nassau/Westchester, 5=Negotiated, 6=Group)
          - name: store_and_fwd_flag
            description: Trip record held in vehicle memory (Y/N)
          - name: payment_type
            description: Payment method (1=Credit card, 2=Cash, 3=No charge, 4=Dispute, 5=Unknown, 6=Voided)
          - name: fare_amount
            description: Time and distance fare
          - name: extra
            description: Miscellaneous extras and surcharges
          - name: mta_tax
            description: MTA tax
          - name: tip_amount
            description: Tip amount (credit card only)
          - name: tolls_amount
            description: Total tolls paid
          - name: improvement_surcharge
            description: Improvement surcharge
          - name: total_amount
            description: Total amount charged